MODEL:
    MODEL_NAME : "conv_net_3"
    MODEL_ARCH: "conv_net_3"
    INPUT_HEIGHT: 58
    INPUT_WIDTH: 58
    CLASSES: 200

TRAIN:
    BATCH_SIZE : 64
    EPOCHS_COUNT : 301
    LEARNING_RATE : 0.001
    KEEP_PROB : 1.0
    TF_RECORDS : ""

VAL:
    BATCH_SIZE : 200
    TF_RECORDS : ""


TEST:
    BATCH_SIZE : 500
    TF_RECORDS : ""
    OUTPUT_PATH : "/data/outputs/tiny_imagenet"