MODEL:
    MODEL_NAME : "vgg_16_net"
    MODEL_ARCH: "vgg_16"
    INPUT_HEIGHT: 58
    INPUT_WIDTH: 58
    CLASSES: 200

TRAIN:
    BATCH_SIZE : 64
    EPOCHS_COUNT : 30001
    LEARNING_RATE : 0.0001
    KEEP_PROB : 0.5
    TF_RECORDS : ""

VAL:
    BATCH_SIZE : 200
    TF_RECORDS : ""


TEST:
    BATCH_SIZE : 200
    TF_RECORDS : ""
    OUTPUT_PATH : "/data/outputs/tiny_imagenet"